[package]
name = "tessera-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
rayon = "1"
tessera = { path = "../tessera" }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread"] }
