[workspace]
resolver = "3"

members = [
    "tessera",
    "tessera-ffi",
    "tessera-derive",
    "tessera-capture",
]

[profile.release]
lto = "fat"
codegen-units = 1

[patch.crates-io]
libmimalloc-sys = { git = "https://github.com/xenondevs/mimalloc_rust", rev = "544382512afc0f8837b40910cfed0db8ff46eea2" }
